---
dist: focal
addons:
  apt:
    packages:
      - python3-pip
      - python3-testresources
      - libssl-dev

language: minimal

services:
  - docker

env:
  global:
    - ROLE_NAME: ansible_python
    - PATH: /home/travis/.local/bin:${PATH}
  matrix:
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.9
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.10
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.11
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.12
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_VERSION: 7
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_VERSION: 8
    - MOLECULE_DISTRO: debian
      MOLECULE_DISTRO_VERSION: 8
    - MOLECULE_DISTRO: debian
      MOLECULE_DISTRO_VERSION: 9
    - MOLECULE_DISTRO: debian
      MOLECULE_DISTRO_VERSION: 10
    - MOLECULE_DISTRO: fedora
      MOLECULE_DISTRO_VERSION: 32
    - MOLECULE_DISTRO: fedora
      MOLECULE_DISTRO_VERSION: 33
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_VERSION: 16.04
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_VERSION: 18.04
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_VERSION: 20.04

install:
  # Upgrade setuptools
  - python3 -m pip install --upgrade --user setuptools
  # Install Ansible Molecule with docker driver and lint tools
  - python3 -m pip install --upgrade --user "molecule[ansible,docker,lint]"

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $(basename $TRAVIS_REPO_SLUG) $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}
  - cd $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}
  # Show Ansible and Molecule versions
  - ansible --version
  - molecule --version

script:
  # Run tests.
  - molecule test

jobs:
  include:
    - stage: trigger container-python
      if: branch = master
      install: skip
      before_script: skip
      script: bash .travis/trigger-job $(dirname $TRAVIS_REPO_SLUG) container-python

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
