---
dist: focal
addons:
  apt:
    packages:
      - libssl-dev
      - libffi-dev
      - python3
      - python3-pip
      - python3-setuptools
      - python3-software-properties
      - python3-wheel

language: minimal

services:
  - docker

env:
  global:
    - ROLE_NAME: ansible_python
  matrix:
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.9
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.10
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.11
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.12
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_VERSION: 6
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_VERSION: 7
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_VERSION: 8
    - MOLECULE_DISTRO: debian
      MOLECULE_DISTRO_VERSION: 8
    - MOLECULE_DISTRO: debian
      MOLECULE_DISTRO_VERSION: 9
    - MOLECULE_DISTRO: debian
      MOLECULE_DISTRO_VERSION: 10
    - MOLECULE_DISTRO: fedora
      MOLECULE_DISTRO_VERSION: 31
    - MOLECULE_DISTRO: fedora
      MOLECULE_DISTRO_VERSION: 32
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_VERSION: 16.04
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_VERSION: 18.04
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_VERSION: 20.04

install:
  # Install test dependencies.
  - pip3 install -U jinja2 requests ansible molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $(basename $TRAVIS_REPO_SLUG) $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}
  - cd $(dirname $TRAVIS_REPO_SLUG).${ROLE_NAME}

script:
  # Run tests.
  - molecule test

jobs:
  include:
    - stage: trigger container-python
      if: branch = master
      install: skip
      before_script: skip
      script: bash .travis/trigger-job $(dirname $TRAVIS_REPO_SLUG) container-python

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
