---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible_python
    - AUTHOR_NAME: coglinev3
  matrix:
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.9-bash
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.10-bash
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.11-bash
    - MOLECULE_DISTRO: coglinev3/alpine
      MOLECULE_DISTRO_VERSION: 3.12-bash
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_VERSION: 6
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_VERSION: 7
    - MOLECULE_DISTRO: centos
      MOLECULE_DISTRO_VERSION: 8
    - MOLECULE_DISTRO: debian
      MOLECULE_DISTRO_VERSION: 8
    - MOLECULE_DISTRO: debian
      MOLECULE_DISTRO_VERSION: 9
    - MOLECULE_DISTRO: debian
      MOLECULE_DISTRO_VERSION: 10
    - MOLECULE_DISTRO: fedora
      MOLECULE_DISTRO_VERSION: 29
    - MOLECULE_DISTRO: fedora
      MOLECULE_DISTRO_VERSION: 30
    - MOLECULE_DISTRO: fedora
      MOLECULE_DISTRO_VERSION: 31
    - MOLECULE_DISTRO: fedora
      MOLECULE_DISTRO_VERSION: 32
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_VERSION: 16.04
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_VERSION: 18.04
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_VERSION: 19.10
    - MOLECULE_DISTRO: ubuntu
      MOLECULE_DISTRO_VERSION: 20.04

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-${ROLE_NAME} ${AUTHOR_NAME}.${ROLE_NAME}
  - cd ${AUTHOR_NAME}.${ROLE_NAME}

script:
  # Run tests.
  - molecule test

jobs:
  include:
    - stage: trigger container-python
      install: skip
      before_script: skip
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          curl -LO --retry 3 https://raw.githubusercontent.com/plume-lib/trigger-travis/master/trigger-travis.sh
          sh trigger-travis.sh --pro coglinev3 container-python $TRAVIS_ACCESS_TOKEN
        else
          echo "trigger-travis.sh did not run"
        fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
