---
# file: roles/ansible_python/tasks/install-python2.yml

# Install Python 2
- name: Install Python 2 when needed on apk based systems
  raw: apk add --no-cache python
  when:
    - apk_system.rc is defined
    - apk_system.rc == 0
- name: Install Python 2 when needed on apt-get based systems
  raw: apt-get install -y python-minimal
  when:
    - apt_system.rc == 0
- name: Install Python 2 when needed on yum based systems
  raw: yum -y install python3
  when:
    - yum_system.rc == 0
- name: Install Python 2 when needed on dnf based systems
  raw: dnf -y install python)
  when:
    - yum_system.rc is not defined
    - dnf_system.rc is defined
    - dnf_system.rc == 0
