---
# file: roles/ansible_python/tasks/install-python2.yml

# Install Python 2
- name: Install Python 2 when needed on apk based systems
  ansible.builtin.raw: apk add --no-cache python
  args:
    executable: /bin/bash
  when:
    - apk_system.rc is defined
    - apk_system.rc == 0
- name: Install Python 2 when needed on apt-get based systems
  ansible.builtin.raw: apt-get install -y --no-install-recommends python-minimal python-apt
  when:
    - apt_system.rc == 0
- name: Install Python 2 when needed on yum based systems
  ansible.builtin.raw: yum -y install python3
  when:
    - yum_system.rc == 0
- name: Install Python 2 when needed on dnf based systems
  ansible.builtin.raw: dnf -y install python)
  when:
    - yum_system.rc is not defined
    - dnf_system.rc is defined
    - dnf_system.rc == 0
