---
# file: roles/ansible_python/tasks/remove-cache.yml

- name: "APT: Remove repository cache"
  ansible.builtin.raw: rm -rf /var/lib/apt/lists/*
  changed_when: false
  args:
    warn: false
  when:
    - apt_system.rc is defined
    - apt_system.rc == 0

- name: "YUM: Remove repository cache"
  ansible.builtin.raw: yum clean all --enablerepo=\*
  changed_when: false
  args:
    warn: false
  when:
    - yum_system.rc is defined
    - yum_system.rc == 0

- name: "DNF: Remove repository cache"
  ansible.builtin.raw: dnf clean all --enablerepo=\*
  changed_when: false
  args:
    warn: false
  when:
    - yum_system.rc is not defined
    - dnf_system.rc is defined
    - dnf_system.rc == 0
