---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/${MOLECULE_DISTRO:-coglinev3/alpine}:${MOLECULE_DISTRO_VERSION:-3.19}
    pre_build_image: ${MOLECULE_DISTRO_PREBUILD:-true}
provisioner:
  name: ansible
  # log: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint tests/test.yml
  flake8
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - check
    - verify
    - destroy
