---
# file: roles/ansible_python/molecule/default/verify.yml

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Discovered pyhton interpreter
      debug:
        msg: "{{ discovered_interpreter_python }}"
    - name: "Get Python Version"
      shell: >
        (platform-python --version 2>&1
        || python3 --version
        || python --version 2>&1
        || echo python not available) | grep -v "not found"
      environment:
        PATH: /usr/local/bin:/bin:/usr/bin:/usr/libexec
      changed_when: false
      failed_when: false
      register: python_version
    - name: "Show Python Version"
      debug:
        msg: "{{ python_version.stdout }}"
      when: python_version.stdout is defined
    - name: Show OS
      debug:
        msg: "{{ ansible_distribution }} - {{ ansible_distribution_version }}"
