#!/usr/bin/env bash

if [[ $# != 2 ]]; then
  echo wrong args
  echo ./trigger-job TRAVIS_USER TRAVIS_JOBNAME
  exit -1
fi

echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
if [[ ($TRAVIS_BRANCH == master) &&
      ($TRAVIS_PULL_REQUEST == false) ]] ; then
  curl -LO --retry 3 https://raw.githubusercontent.com/plume-lib/trigger-travis/master/trigger-travis.sh
  bash trigger-travis.sh --pro $1 $2 $TRAVIS_ACCESS_TOKEN
else
  echo "trigger-travis.sh did not run"
fi
