---
name: Build

# Controls when the workflow will run
'on':
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#  schedule:
#    - cron: "47 3 * * 0"

defaults:
  run:
    working-directory: 'coglinev3.ansible_python'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'coglinev3.ansible_python'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Lint code with yamllint.
        run: yamllint .

      - name: Lint code with ansible-lint.
        run: ansible-lint

  # Test the Ansible role with Molecule
  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: coglinev3/alpine
            distro_version: '3.12'
          - distro: coglinev3/alpine
            distro_version: '3.13'
          - distro: coglinev3/alpine
            distro_version: '3.14'
          - distro: coglinev3/alpine
            distro_version: '3.15'
          - distro: coglinev3/alpine
            distro_version: '3.16'
          - distro: coglinev3/alpine
            distro_version: '3.17'
          - distro: centos
            distro_version: '7'
          - distro: almalinux
            distro_version: '8'
          - distro: almalinux
            distro_version: '9'
          - distro: debian
            distro_version: '10'
          - distro: debian
            distro_version: '11'
          - distro: fedora
            distro_version: '34'
          - distro: fedora
            distro_version: '35'
          - distro: fedora
            distro_version: '36'
          - distro: fedora
            distro_version: '37'
          - distro: ubuntu
            distro_version: '16.04'
          - distro: ubuntu
            distro_version: '18.04'
          - distro: ubuntu
            distro_version: '20.04'
          - distro: ubuntu
            distro_version: '22.04'

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'coglinev3.ansible_python'


      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip python3-testresources libssl-dev

      - name: Upgrade Python wheel
        run: python3 -m pip install --upgrade --user wheel

      - name: Upgrade Python setuptools
        run: python3 -m pip install --upgrade --user setuptools

      - name: Install Ansible Molecule with docker driver and lint tools
        run: python3 -m pip install --upgrade --user ansible ansible-lint "molecule[docker,lint]"

      - name: Configure Ansible
        run: |
          mkdir -p ~/.ansible
          cp .github/ansible.cfg ~/.ansible.cfg
          cp .github/hosts ~/.ansible/hosts

      - name: Show Ansible and Molecule version
        run: |
          ansible --version
          molecule --version

      - name: Run tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_DISTRO_VERSION: ${{ matrix.distro_version }}
          ANSIBLE_ROLES_PATH: ~/.ansible/molecule/roles

  # Push Ansible role to Ansible Galaxy
  release:
    name: Release
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
